apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  mongo-init.js: |
    db.createUser(
      {
        user: "admin",
        pwd: "adminnew123",
        roles: [ { role: "readWrite", db: "database" } ]
      }
    )
    db.createCollection("caminhoes")
    db.caminhoes.createIndex({ "placa": 1 }, { unique: true })
