architecture: standalone

auth:
  enabled: true
  rootPassword: "root"
  username: "admin"
  password: "adminnew123"
  database: "database"

persistence:
  enabled: true
  size: 8Gi
  accessMode: ReadWriteOnce

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

service:
  type: ClusterIP
  port: 27017

metrics:
  enabled: false

livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 20
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 6
    
readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 20
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 6

security:
  authorization: enabled
  javascriptEnabled: false

extraFlags:
  - "--logpath=/dev/stdout"
  - "--logappend"
  - "--verbose"
  - "--auth"

extraEnvVars:
  - name: MONGODB_ENABLE_JOURNAL
    value: "true"
  - name: MONGODB_SYSTEM_LOG_VERBOSITY
    value: "2"
  - name: MONGODB_NET_MAX_INCOMING_CONNECTIONS
    value: "10000"
  - name: MONGODB_NET_KEEP_ALIVE_TIME_MS
    value: "120000"

extraVolumes:
  - name: init-script
    configMap:
      name: mongodb-config

extraVolumeMounts:
  - name: init-script
    mountPath: /docker-entrypoint-initdb.d
