apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "servico-localizacao.fullname" . }}
  labels:
    {{- include "servico-localizacao.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "servico-localizacao.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "servico-localizacao.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
            - name: udp
              containerPort: {{ .Values.service.udpPort }}
              protocol: UDP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
