apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "servico-localizacao.fullname" . }}
  labels:
    {{- include "servico-localizacao.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "servico-localizacao.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "servico-localizacao.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
            - name: udp
              containerPort: {{ .Values.service.udpPort }}
              protocol: UDP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: RABBITMQ_HOST
              value: {{ .Values.rabbitmq.host | quote }}
            - name: RABBITMQ_PORT
              value: {{ .Values.rabbitmq.port | quote }}
            - name: RABBITMQ_USERNAME
              value: {{ .Values.rabbitmq.username | quote }}
            - name: RABBITMQ_PASSWORD
              value: {{ .Values.rabbitmq.password | quote }}
            - name: RABBITMQ_QUEUE_NAME
              value: {{ .Values.rabbitmq.queue.name | quote }}
            - name: RABBITMQ_EXCHANGE_NAME
              value: {{ .Values.rabbitmq.exchange.name | quote }}
            - name: RABBITMQ_ROUTING_KEY
              value: {{ .Values.rabbitmq.routing.key | quote }}
