replicaCount: 1

image:
  repository: cassandra
  tag: 3.11

persistence:
  enabled: true
  storageClass: "hostpath"
  size: 8Gi

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 0.5
    memory: 1Gi

# Desabilitar métricas e JMX
metrics:
  enabled: false

cassandra:
  extraEnvVars:
    - name: MAX_HEAP_SIZE
      value: "1024M"
    - name: HEAP_NEWSIZE
      value: "256M"

# Desabilitar probes temporariamente
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false