replicaCount: 1

image:
  repository: cassandra
  tag: 3.11

persistence:
  enabled: true
  storageClass: "hostpath"
  size: 8Gi

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# Desabilitar métricas e JMX
metrics:
  enabled: false

cassandra:
  extraEnvVars:
    - name: MAX_HEAP_SIZE
      value: "1024M"
    - name: HEAP_NEWSIZE
      value: "256M"
    - name: CASSANDRA_SEEDS
      value: "cassandra-0.cassandra.default.svc.cluster.local"
    - name: CASSANDRA_CLUSTER_NAME
      value: "MyCassandraCluster"
    - name: CASSANDRA_DC
      value: "DC1"
    - name: CASSANDRA_RACK
      value: "Rack1"
    - name: CASSANDRA_ENDPOINT_SNITCH
      value: "GossipingPropertyFileSnitch"

# Desabilitar probes temporariamente
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false