{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "servico-gerenciador-consumidor.fullname" . }}-role
  labels:
    {{- include "servico-gerenciador-consumidor.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "servico-gerenciador-consumidor.fullname" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "servico-gerenciador-consumidor.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "servico-gerenciador-consumidor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "servico-gerenciador-consumidor.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}