service:
  type: NodePort

management:
  service:
    type: NodePort

auth:
  enabled: true
  username: "admin"
  password: "adminpassword"  
  erlangCookie: "CHANGE_ME"  

plugins:
  - rabbitmq_auth_mechanism_ssl
  - rabbitmq_auth_backend_ldap
  - rabbitmq_management

persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

extraConfiguration: |
  auth_mechanisms.1 = PLAIN
  auth_mechanisms.2 = AMQPLAIN
  listeners.tcp.default = 5672
  loopback_users = none

extraVolumeMounts:
  - name: definitions
    mountPath: /app/custom_definitions.json
    subPath: custom_definitions.json

extraVolumes:
  - name: definitions
    configMap:
      name: rabbitmq-definitions

permissions:
  - user: admin
    vhost: /
    read: ".*"
    write: ".*"
    configure: ".*"