fullnameOverride: "rabbitmq"

auth:
  username: "admin"
  password: "adminnew123"
  erlangCookie: "SWQOKODSQALRPCLNMEQG"

service:
  type: NodePort
  nodePorts:
    amqp: ""
    manager: "32747"

persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

extraPlugins: "rabbitmq_management,rabbitmq_prometheus"

management:
  enabled: true

metrics:
  enabled: true

tls:
  enabled: false

extraConfiguration: |
  management.tcp.port = 15672