apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "servico-consumidor-para-caminhao.fullname" . }}
  labels:
    {{- include "servico-consumidor-para-caminhao.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "servico-consumidor-para-caminhao.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "servico-consumidor-para-caminhao.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.env | nindent 12 }}