apiVersion: apps/v1
kind: Deployment
metadata:
  name: servico-notificacoes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: servico-notificacoes
  template:
    metadata:
      labels:
        app: servico-notificacoes
    spec:
      containers:
      - name: servico-notificacoes
        image: seu-registro/servico-notificacoes:latest
        ports:
        - containerPort: 8084
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq"
        - name: ELASTICSEARCH_HOST
          value: "elasticsearch"
