apiVersion: apps/v1
kind: Deployment
metadata:
  name: servico-localizacao
spec:
  replicas: 2
  selector:
    matchLabels:
      app: servico-localizacao
  template:
    metadata:
      labels:
        app: servico-localizacao
    spec:
      containers:
      - name: servico-localizacao
        image: seu-registro/servico-localizacao:latest
        ports:
        - containerPort: 8082
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq"
        - name: ELASTICSEARCH_HOST
          value: "elasticsearch"